// <auto-generated />
using System;
using ConsoleAppReorderingProblem.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppReorderingProblem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230727135345_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleAppReorderingProblem.Domain.RegisteredDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousDeviceId")
                        .IsUnique()
                        .HasFilter("[PreviousDeviceId] IS NOT NULL");

                    b.ToTable("RegisteredDevice", (string)null);
                });

            modelBuilder.Entity("ConsoleAppReorderingProblem.Domain.RegisteredDevice", b =>
                {
                    b.HasOne("ConsoleAppReorderingProblem.Domain.RegisteredDevice", "PreviousDevice")
                        .WithOne()
                        .HasForeignKey("ConsoleAppReorderingProblem.Domain.RegisteredDevice", "PreviousDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PreviousDevice");
                });
#pragma warning restore 612, 618
        }
    }
}
