// <auto-generated />
using System;
using ConsoleAppReorderingProblem.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppReorderingProblem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsoleAppReorderingProblem.Domain.RegisteredDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousDeviceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousDeviceId")
                        .IsUnique()
                        .HasFilter("[PreviousDeviceId] IS NOT NULL");

                    b.ToTable("RegisteredDevice", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceName = "J. J. Keller ELD - iOS 2.0",
                            ModelNumber = "20I",
                            Position = 0
                        },
                        new
                        {
                            Id = 2,
                            DeviceName = "J. J. Keller ELD - iOS 2.5",
                            ModelNumber = "25I",
                            Position = 1,
                            PreviousDeviceId = 1
                        },
                        new
                        {
                            Id = 3,
                            DeviceName = "#1 ELD by HOS247",
                            ModelNumber = "FLT3",
                            Position = 2,
                            PreviousDeviceId = 2
                        },
                        new
                        {
                            Id = 4,
                            DeviceName = "Xpert ELD",
                            ModelNumber = "N775G",
                            Position = 3,
                            PreviousDeviceId = 3
                        },
                        new
                        {
                            Id = 5,
                            DeviceName = "PeopleNet Mobile Gateway - Trimble Driver ELD",
                            ModelNumber = "PMG001",
                            Position = 4,
                            PreviousDeviceId = 4
                        });
                });

            modelBuilder.Entity("ConsoleAppReorderingProblem.Domain.RegisteredDevice", b =>
                {
                    b.HasOne("ConsoleAppReorderingProblem.Domain.RegisteredDevice", "PreviousDevice")
                        .WithOne()
                        .HasForeignKey("ConsoleAppReorderingProblem.Domain.RegisteredDevice", "PreviousDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("PreviousDevice");
                });
#pragma warning restore 612, 618
        }
    }
}
